# Generated by Django 3.1.1 on 2020-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200928_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
